# Generated by Django 4.2.7 on 2025-09-10 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название объекта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('customer', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date_plan', models.DateField(verbose_name='Плановая дата завершения')),
                ('end_date_actual', models.DateField(blank=True, null=True, verbose_name='Фактическая дата завершения')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('in_progress', 'В работе'), ('on_hold', 'На паузе'), ('completed', 'Завершен')], default='planning', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Строительный объект',
                'verbose_name_plural': 'Строительные объекты',
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отчета')),
                ('volume_completed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выполненный объем')),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crm_core.constructionsite', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Ежедневный отчет',
                'verbose_name_plural': 'Ежедневные отчеты',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование работы')),
                ('unit', models.CharField(choices=[('m2', 'м²'), ('m3', 'м³'), ('pcs', 'шт.')], max_length=10, verbose_name='Единица измерения')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость за единицу')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_core.worktype', verbose_name='Родительский вид работы')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ',
            },
        ),
        migrations.CreateModel(
            name='EmployeeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Отработано часов')),
                ('daily_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_works', to='crm_core.dailyreport')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_core.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Работа сотрудника',
                'verbose_name_plural': 'Работы сотрудников',
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm_core.worktype', verbose_name='Вид работы'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='crm_core.employee', verbose_name='Прораб'),
        ),
    ]
